"use server";

import nodemailer from "nodemailer";

export async function sendEmail(formData) {
  const firstName = formData.get("firstName");
  const lastName = formData.get("lastName");
  const email = formData.get("email");
  const message = formData.get("message");

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,          
      pass: process.env.GMAIL_APP_PASSWORD,  
    },
  });

  const mailOptions = {
    from: email,
    to: "kuraoshen@gmail.com", 
    subject: `⚡ New Project Inquiry from ${firstName} ${lastName}`,
    text: `You have a new message from ${firstName} ${lastName} (${email}): ${message}`,
    
    html: `
      <div style="padding: 40px 20px; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #f3f4f6; min-height: 100%;">
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: #0b0726; border: 1px solid #1f1a4a; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.5);">
          
          <tr>
            <td style="background: linear-gradient(135deg, #0ea5e9 0%, #6366f1 100%); padding: 35px 40px; text-align: center;">
              <p style="margin: 5px 0 0 0; color: #e0e7ff; font-size: 20px; font-weight: 300; letter-spacing: 1px; text-transform: uppercase;">
                Portfolio Message Received
              </p>
            </td>
          </tr>

          <tr>
            <td style="padding: 40px;">
              <p style="margin: 0 0 24px 0; font-size: 16px; line-height: 1.6; color: #9ca3af;">
                Hi Luthfi, someone just filled out the contact form on your portfolio website. Here are the details:
              </p>

              <table width="100%" style="background-color: #130f35; border-radius: 12px; margin-bottom: 30px; border-collapse: separate;" cellpadding="15">
                <tr>
                  <td width="30%" style="color: #38bdf8; font-weight: 600; font-size: 14px; border-bottom: 1px solid #1f1a4a;">Sender Name</td>
                  <td width="70%" style="color: #ffffff; font-size: 15px; border-bottom: 1px solid #1f1a4a; font-weight: 500;">
                    ${firstName} ${lastName}
                  </td>
                </tr>
                <tr>
                  <td style="color: #38bdf8; font-weight: 600; font-size: 14px;">Email Address</td>
                  <td>
                    <a href="mailto:${email}" style="color: #FFFFFF; text-decoration: none; font-size: 15px; font-weight: 500;">
                      ${email}
                    </a>
                  </td>
                </tr>
              </table>

              <h4 style="margin: 0 0 10px 0; color: #38bdf8; font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">
                Message Content:
              </h4>
              <div style="background-color: #000000; border-left: 4px solid #0ea5e9; padding: 20px; border-radius: 0 12px 12px 0; font-size: 15px; line-height: 1.6; color: #e5e7eb; font-style: italic;">
                "${message.replace(/\n/g, '<br>')}"
              </div>
              
              <div style="text-align: center; margin-top: 35px;">
                <a href="mailto:${email}" style="background-color: #0ea5e9; color: #ffffff; padding: 12px 30px; text-decoration: none; font-size: 14px; font-weight: 600; border-radius: 8px; display: inline-block; transition: background 0.2s;">
                  Reply to Sender Directly
                </a>
              </div>
            </td>
          </tr>

          <tr>
            <td style="padding: 20px 40px; background-color: #06021f; border-top: 1px solid #1f1a4a; text-align: center; font-size: 12px; color: #6b7280;">
              <p style="margin: 0 0 4px 0;">This email was automatically generated by your Next.js Luthfi's portfolio app.</p>
              <p style="margin: 0;">© ${new Date().getFullYear()} KuraoShen. All rights reserved.</p>
            </td>
          </tr>

        </table>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    return { success: true, message: "Message sent successfully" };
  } catch (error) {
    console.error("Nodemailer Error:", error);
    return { success: false, message: "Failed to send message; please try again or check your network" };
  }
}